### PR TITLE
Creates forgiver strategy

### PR DESCRIPTION
**Pull request by uglyfruitcake**

### CODE REVIEW

**Comment by drvinceknight** [comment]
Thanks for this @uglyfruitcake , any chance that you could write some tests? Take a look at this test script might give you an idea of what to do: https://github.com/drvinceknight/Axelrod/blob/master/axelrod/tests/test_titfortat.py

If that's too tricky though let me know and I'll either help or write the tests.

**Comment by uglyfruitcake** [comment]
Ok, I've never written any unit tests but I've had a quick look and I'll give it a go.

**Comment by drvinceknight** [comment]
I thought so :) Let me know if I can help (I'm sure there's someone else around that you could ask also).

To run the tests:

```
python -m unittest discover axelrod/tests/
```

:+1:

**Comment by uglyfruitcake** [comment]
Ok, I've added the tests and fixed the merge conflicts.

**Comment by drvinceknight** [comment]
Looks great! Thanks!

**Pull request merged**
