### PR TITLE
Adds Limited retaliate strategy

### PR DESCRIPTION
**Pull request by meatballs**

### CODE REVIEW

**Comment by drvinceknight** [comment]
Looks great @meatballs , could you just add a test for your new init method? I know that it is super simple but just want to make sure every thing is well tested... (Planning on going through and making sure all the strategies even have their init tested).

**Comment by meatballs** [comment]
All sorted now

**Comment by drvinceknight** [comment]
Thanks :)

**Comment by drvinceknight** [comment]
I don't seem able to 're-open' this. I think you'll need to send me another pull request. Apologies for the confusion, my fault entirely, I just clicked merge on my phone but I think I'd feel better if there was a `reset` method (tested) as I describe here: #64 

Sorry for the confusion.

**Pull request merged**
