### PR TITLE
Adds use of abc module for Player class

### PR DESCRIPTION
**Pull request by meatballs**
Makes the Player class a true Abstract Base Class with the abc module
Adds an AxelrodTestCase class with a concrete test implementation of Player
Alters tests to use AxelrodTestCase and testPlayer

### CODE REVIEW

**Comment by drvinceknight** [comment]
Thanks for this @meatballs , again very little that I know about. What is the main advantage of using this?

**Comment by meatballs** [comment]
Well, that's a matter of some debate!! 

I did it simply because the class claimed to be abstract (in its comments) and this implements that claim for definite.

Personally, I think it's clearer if the intention (that a Player subclass must have a name and a strategy) is in the code, and therefore enforced, rather than simply in a comment.

Feel free to disregard if you're a pure duck typing man!

**Comment by langner** [comment]
> I did it simply because the class claimed to be abstract (in its comments)

Who added that comment? That would me :) I didn't think much of it at the time and had no intention  to really make it abstract. But that would be the role of this class here, right? Namely, it's not meant to play at all.

**Comment by meatballs** [comment]
I think so. Could be my age, therefore previous exposure to static typed languages, but it seems cleaner somehow

**Comment by drvinceknight** [comment]
I'm very happy to add this in, I've just gotten back from a DjangoCon Europe organisation meeting @meatballs (very likely to be an Axelrod sprint :)) so haven't had time to look through this to carefully. There doesn't seem to be any negative side to adding this in though right? 

From the point of view of a contributor who does perhaps not know the 'ins and outs' of this abstraction (I'm putting my hand up here) it doesn't add any further confusion right?

**Comment by drvinceknight** [comment]
Does this relate to #45 (which I still haven't read through carefully - apologies but want to make sure I don't rush it) or am I more confused than I thought I was?

**Comment by meatballs** [comment]
I'm not sure it's a great idea to introduce stuff that's not well understood by all - especially when it's not adding any huge benefit. Let's dump it for now.

It does indeed relate to #45, but it might be worth doing the whole of #45 in one go rather than piecemeal like this. Sorry if I've ended up causing confusion!!

**Comment by drvinceknight** [comment]
No apologies needed at all: this is awesome. I'll leave the pull request open and try over the next couple of days to wrap my head around it better: if nothing else I really appreciate the opportunity to learn something.

Will get back to you asap @meatballs :)

**Comment by meatballs** [comment]
I closed this as I made the schoolboy error of creating it on my master branch which causes all sorts of problems if it's not merged in.

I'll create a separate 'abc' branch for this change.

**Pull request closed without merging**
