### PR TITLE
Adding grumpy.py

### PR DESCRIPTION
**Pull request by JasYoung314**
Adding grumpy. This strategy chooses a strategy based on two thresholds which depend on the history of the opponent.

### CODE REVIEW

**Comment by drvinceknight** [comment]
Hi @JasYoung314 thanks a lot for the pull request: the grumpy strategy looks cool (thanks also for the tests!).

I note that the strategy keeps another attribute (the state: grumpy or not). This is something that will need to be reset at every repetition of a duel in the tournament. I've actually just changed how reset works with this commit: 3d061048ae30f1f836efe94201fe3326e2024a11

Could you add a specific reset method to the `Grumpy` class so that it not only resets `history` and `score` but also the state (you'll have to add the method so that it overwrites the `reset` method it inherits).

**Comment by drvinceknight** [comment]
(this commit also: 376d9cf587b6adbe95b4c8fa5d0c630682653e4c)

**Comment by JasYoung314** [comment]
Thanks @drvinceknight I have made the change to the grumpy player class you requested.

**Comment by drvinceknight** [comment]
Nice: could you just add a test for the reset method in the grumpy class? Once you've done that I'll merge!

**Comment by JasYoung314** [comment]
@drvinceknight the reset method is now tested for grumpy

**Pull request merged**
