### PR TITLE
Memory-One strategies including WSLS, Zero Determinant, and a few others

### PR DESCRIPTION
**Pull request by marcharper**
Some new strategies, all memory-one, including WSLS and a few zero determinants. There's a generic MemoryOne class that one can use to specify the four probabilities P(C+CC), P(C|CD), P(C|DC), and P(C|DD), and an initial state.

Some of the other strategies (TFT, GTFT, ALLD, ALLC, etc.) could be subclassed, but in many cases the existing implementations are more efficient (including WSLS).

### CODE REVIEW

**Comment by drvinceknight** [comment]
This looks really cool @marcharper. It's missing tests though, are you OK to write them or would you like me to?  (I should be able to get around to it over the next couple of days)

**Comment by marcharper** [comment]
I'm traveling for the next few days but if I have time I'll make some upgrades. Also I'm going to move the game matrix in tournament.py outside of calculate_scores so I can use the Press and Dyson determinant to calculate actual ZD strategies.

**Comment by drvinceknight** [comment]
Ok, could you not just grab the payoff matrix by calling a tournament instance? A couple of other strategies do it this way (I might be misunderstanding). Either way I think it would be good if that was a separate pull request? For this one if you're happy to write the tests that's great but let me know if you'd like me to :)

**Comment by marcharper** [comment]
Ok, I added a few more strategies and tests for most of them. Some of the stochastic strategies are not easy to test! (My flight was delayed so I had some time to work on this.)

I did not see any easy way to access the game matrix without pulling it out of the score function, but it doesn't seems to affect any other strategy adversely. So I'll leave that decision up to you.

**Comment by drvinceknight** [comment]
That's awesome Marc! I'll look through this sometime today or early
tomorrow. Really appreciate the contribution! Safe travels.

**Comment by drvinceknight** [comment]
Haven't gotten around to this yet but haven't forgotten (just swamped by marking/teaching). Will get to is asap. Apologies!

**Comment by drvinceknight** [comment]
Fighting with this now :smile: I have a messy merge conflict (not anyone's fault) so will hopefully get somewhere soon :+1:

**Comment by drvinceknight** [comment]
@marcharper , I'm struggling with time but would really love this to be included. If you could fix the merge conflicts (there have been a bunch of changes recently one which should actually make it simpler for you to pull out the utilities) that would be great. If not, I promise I will get to this eventually (sorry!).

**Comment by drvinceknight** [comment]
Hi @marcharper, 5 of these have been merged in. I've commented 2 out as I wouldn't mind these two being a seperate pull request just so that we can discuss (mainly because I am unfamiliar with them). I've raised an issue in case anyone else wanted to take a look: #102 

The commit that commented the strategies out is here: fa579594cf8e285a05a0cf4808d1133aaebdb771

**Pull request merged**
