### PR TITLE
Added Average_Copier strategy (no tests sorry)

### PR DESCRIPTION
**Pull request by geraintpalmer**

### CODE REVIEW

**Comment by drvinceknight** [comment]
@geraintpalmer my polite 'dont worry if there are no tests' doesn't apply for you: write a test :)

**Comment by geraintpalmer** [comment]
done I think.

**Comment by drvinceknight** [comment]
Looks good @geraintpalmer , you have commited your .DS_Store files though. Can you remove these from the history (ask @JasYoung314 how to do that) and add them to the gitignore (this shows the danger of  `add .` or similar).

I'm guessing all tests have passed? Once you've done that I'll merge.

**Comment by drvinceknight** [comment]
Seems like you managed to remove some of the .DS_Store files but that there's one left: can you do whatever you did to that one? (Click on Files changed on this page and you'll see what I mean).

**Comment by geraintpalmer** [comment]
thats not showing up on mine; no .DS_Store files there

**Comment by drvinceknight** [comment]
Cool, I'll just merge it and we'll see what happens. Thanks Geraint! Nice
strategy, I look forward to the learning one.

**Comment by geraintpalmer** [comment]
Thanks. Sorry for being a pain. Making strategies are fun!

**Comment by drvinceknight** [comment]
Not at all a pain: I appreciate you taking the time. But be aware with `git
add .`: don't do it basically.

**Pull request merged**
