### PR TITLE
Added the Reflex strategy.

### PR DESCRIPTION
**Pull request by pmslavin**
Added "The Reflex", a simple strategy which considers the outcome of the previous round before adjusting its next response accordingly.  Basic tests are provided.

### CODE REVIEW

**Comment by drvinceknight** [comment]
This looks really good @pmslavin, very happy to merge although this commit 297f69d5f2ff4752d5b603ab4025782f2e26eae2 has just streamlined the test suite. Do you reckon you could make the corresponding modifications? (Sorry to be a pain)

**Comment by pmslavin** [comment]
OK - no problem. d0c4da7 uses the new TestPlayer class.

**Comment by drvinceknight** [comment]
That commit actually simplified the tests a lot so you can write them just like this now: https://github.com/drvinceknight/Axelrod/blob/master/axelrod/tests/test_defector.py

The `TestPlayer` class takes care of the init and repr for example: https://github.com/drvinceknight/Axelrod/blob/master/axelrod/tests/test_titfortat.py

if you could just throw those out I'll go on ahead and merge :+1: (sorry for being a pain)

**Comment by pmslavin** [comment]
I see :) e5e068c takes the redundant tests out of the derived class.

**Comment by drvinceknight** [comment]
Very grateful :+1: :joy:

**Comment by drvinceknight** [comment]
I've just updated the results and reflex has jumped straight to the top spot! 73ba195827edf5ddeeaa6fa0a42eaf621e8c9dd0

**Comment by pmslavin** [comment]
Super.  The name is partly due to the 'Reflexive' element in considering the outcome resulting from its own previous behaviour, and part Duran Duran :sunglasses:

**Comment by drvinceknight** [comment]
Haha very cool, I'm going to throw a couple more tests in for it at some
point (just letting you know). Thanks for the contribution! :)

**Comment by drvinceknight** [comment]
@pmslavin so sorry but I've had to revert this PR, @geraintpalmer pointed out that this strategy corresponded to grudger. I really should have noticed this myself.

**Comment by pmslavin** [comment]
Yes, I've taken a look and I can see the equivalence - I should have checked more thoroughly!
I'm travelling at the moment but might attempt another contribution next week.

**Pull request merged**
