### PR TITLE
Geller bot

### PR DESCRIPTION
**Pull request by martinjc**
Geller is a bot with a 'mind-reading' strategy - it reads the mind of the opponent and responds based on whatever their next move will be.

As I mentioned in the comment, this is almost certainly 'cheating', but it works pretty well:

results

### CODE REVIEW

**Comment by drvinceknight** [comment]
Hehe, this has actually just been pipped to the post by @JasYoung314 da20141dfbf210784210cbb84d20364bdd04529f

His strategy basically grabs the opponent and simulate a couple of rounds. As a result of it though, in the pull request I asked him to change the `axelrod/__init__.py` file so that it creates a separate list of strategies that 'cheat'. Your will be the second one :)

(He was also motivated by the RPS talk given by Matt Williams!)

I can't merge this request directly anymore because of the change to that __init__.py file. Could you make the necessary change to that (you'll need to pull from upstream etc...)?

(PS If you could write the test that would be pretty awesome... but no worries if you're busy)

**Comment by drvinceknight** [comment]
(You can see the results with @JasYoung314's cheating strategy here:


)

(The readme has now been updated)

**Comment by martinjc** [comment]
Ha, great minds etc...

Have pulled the new __init__ and merged the changes, so hopefully you can merge this request now.

**Comment by drvinceknight** [comment]
Ok! That's all done now @martinjc (I've written simple tests and tweaked your code slightly - hope that's ok).

An issue has arisen in that @JasYoung314's mind reader and geller can't play nice together. Because geller is 'more elegant' and 'less cheaty' I have put that in and basically removed mindreader for now ( @JasYoung314 suggested it and will be figuring out a way to get it back in). I've created a cheaters branch for posterity (no one should work on that) which is how things were when geller and mindreader couldn't play nice.

Thanks a lot for contributing @martinjc ! I look forward to seeing what the d3 stuff looks like: that's something I need to know how to use more...

**Pull request merged**
