### PR TITLE
Abstracts the Game to a separate class

### PR DESCRIPTION
**Pull request by meatballs**

### CODE REVIEW

**Comment by meatballs** [comment]
This improves the separation of concerns and makes the game matrix available:

```python
import axelrod
g = axelrod.Game()
print g.scores
```
yields:
`{('C', 'D'): (5, 0), ('D', 'C'): (0, 5), ('D', 'D'): (4, 4), ('C', 'C'): (2, 2)}`

**Comment by meatballs** [comment]
Just noticed that @marcharper did something similar in #52 
I'll alter the class so that it behaves in a similar fashion

**Comment by meatballs** [comment]
dunfiddlin!

**Comment by meatballs** [comment]
dunfiddlin!

**Comment by drvinceknight** [comment]
This is very elegant.

**Comment by meatballs** [comment]
Thank you kindly, sir!

**Comment by drvinceknight** [comment]
@geraintpalmer take a look at this one, this might make how you've written your Qlearners a bit more elegant.

**Pull request merged**
