### PR TITLE
Creates Tournament class

### PR DESCRIPTION
**Pull request by meatballs**
I've refactored Axelrod slightly to create a Tournament and RoundRobin class and altered run_tournament.py (and a couple of strategies) to use it.

run_tournament.py is working fine, but the test suite needs a lot of changes and I haven't done that yet.

Let me know if you think this looks worthwhile and I'll go through the tests and alter them to fit.

### CODE REVIEW

**Comment by drvinceknight** [comment]
Yeah I thinks this look like a very nice refactor. I'd offer to help with the test suite but not sure when I'd be able to get to it. Currently trying to get #52 merged in.

**Comment by meatballs** [comment]
OK, I'll get on with it!

I'll commit and push often, so that you can see what I'm up to, but I'll leave with at least one failing test until I'm happy with it.

**Comment by drvinceknight** [comment]
Great: just let me know when it's good to go :)

**Comment by meatballs** [comment]
I've fixed up the existing test so that it all works.

However, I think this change opens the opportunity to refactor the tests themselves. Would you prefer that to happen before this PR is merged or to merge as-is and open a new PR for the test refactoring?

**Comment by drvinceknight** [comment]
Let's merge as is and rewrite the test suite in another PR if that's ok.
Small incremental changes. Whilst writing this travis returned a fail so I'll wait for that to be fixed before merging if that's ok?

**Comment by meatballs** [comment]
Yep, that's just the dummy test that I left in so that it didn't look like I was finished. I'll clear that out now and push it again.

**Comment by drvinceknight** [comment]
:+1: :fireworks:

**Comment by meatballs** [comment]
Nice to get that one off my chest. It's been bugging me for days!!

**Comment by drvinceknight** [comment]
It's great to have in here! It's a very nice contribution. I've been thinking about perhaps have separate files for some of these just to keep things modular.

So perhaps a `player.py` and a `round_robin.py` etc... What do you think?

**Comment by meatballs** [comment]
Definitely!! I resisted doing so only because it seemed to break the convention in place.

The tests ought to be broken out too. Also, I'd like to break down the RoundRobin play method into separate functions that can be tested individually.

**Comment by meatballs** [comment]
I'm on a roll at the moment (and twiddling my thumbs waiting for a client to get back to me) so I'll get it done now.

**Comment by drvinceknight** [comment]
That's very much appreciated :) :+1: If you could keep both those two things as separate PRs that would be appreciated (if it ends up not making sense to do so then don't worry about it).

**Pull request merged**
