### PR TITLE
Introducing meta players

### PR DESCRIPTION
**Pull request by langner**
This abstracts the core of MetaHunter into an abstract MetaPlayer and adds some more involved metaplayers. Depending on the interpretation, these meta players could be regarded as cheaters, since they load other strategies at runtime. They do not, however, modify strategies or run separate tournaments, just record the running scores these strategies would have had in the current game. In princple, the same could be written explicitely without importing the strategies (alhtough it would be much longer). Anyway, these players are not particularly good (I though MetaWinner would do somewhat better, though).

### CODE REVIEW

**Comment by drvinceknight** [comment]
Yeah, I agree: I don't think these count as cheaters. They're just taking very detailed notes throughout the tournament.

**Comment by langner** [comment]
They also boost the walltime of the tournament... creating more optimization challenges! :)

**Comment by drvinceknight** [comment]
Have you seen #125 ? I seem to be having problems with the parallelised version of the tournament now...

**Comment by drvinceknight** [comment]
(That's not directly relevant to this PR but just pinging you in case you have the same problem. Heading out the door now but will take a look at this shortly.)

**Comment by drvinceknight** [comment]
This is looking nice.

How much longer is the run time?

Also, could you tweak the contribution guidelines in the docs for the change from `__init__` to  `_strategies`.

**Comment by langner** [comment]
The whole thing now runs in about 100s on my machine.

**Pull request merged**
