### PR TITLE
Autogenerate strategies for docs

### PR DESCRIPTION
**Pull request by langner**

### CODE REVIEW

**Comment by drvinceknight** [comment]
Am I understanding this right: that make file gets run by readthedocs so it will auto generate the strategies.rst file?

**Comment by langner** [comment]
Yes, it should. If there is a problem, we can remove that dependency and build `strategies.rst` by running `make strategies` and commiting it whenever needed.

**Comment by drvinceknight** [comment]
Or do I need to run `make strategies` to rebuild the `strategies.rst` file? and if so, does that take in to account dependencies as long as a strategy has been added to the `axelrod/strategies` directory?

Have merged in to master either way :)

:+1:

**Comment by drvinceknight** [comment]
The next PR I get for a strategy: I won't modify the `strategies.rst` file and see what happens...

**Comment by langner** [comment]
I'm not entirely sure how readthedocs works internally, but if it runs `make html` with unmodified modification times it should build `strategies.rst` as well, since I added it to the dependencies of the `html` target. Still, updating `strategies.rst` in the repo is not a bad idea.

**Comment by drvinceknight** [comment]
Sweet sweet sweet :)

This is much awesome :)

**Pull request merged**
