### PR TITLE
Add GoByRecentMajority10

### PR DESCRIPTION
**Pull request by langner**

### CODE REVIEW

**Comment by langner** [comment]
Will add test in a moment.

**Comment by drvinceknight** [comment]
Sorry: I missed your comment and about ten minutes ago started working on the tests myself! I apologise: I should have just asked you to do it but I've been merging a bunch of pull requests today with people not able to write tests so I just jumped in and did it: 

- Changed name of file: f3e32866d0b1bd94e784fa4ba47eb769bba570d6
- Added test: 1e874374753ccc18dfa4ee91c07e8385f521d4f4
- Grabbed new results (very cool: you tip tit-for-tat to the top of the pile): 77692c978eb4e979cf3ad8babe9637774722c7a8

Is this ok for me to close or would you prefer to make your own modifications?

**Comment by drvinceknight** [comment]
Just looked at your commits and your tests are much more elegant than mine :)

**Comment by drvinceknight** [comment]
Could you perhaps pull from upstream and replace with your tests?

**Comment by langner** [comment]
Whatever works for you. I put the class in a generically named file, because it makes sense to group strategies if GoByRecentMajority20 or GoByRecentMajority5 turn out better. That depends on how much diversity you want.

**Comment by drvinceknight** [comment]
Ah yes! That's an excellent point re files names! If you don't mind making that change back (including the file names) that would be great. Perhaps even throw in a GoByRecentMajority5? (I could do that myself if easier).

(Apologies again for the confusion)

**Comment by langner** [comment]
No Problemo! I added some more version, and abstracted GoByMajority to include the case with limited memory, to make things simpler.

I don't know about the tipping, though. The order at the top still seems quite random...

**Comment by drvinceknight** [comment]
That all looks awesome. Yeah still a lot of stochasticity but they're ordered in terms of the median score (axelrod originally used the mean). Thanks a lot for this contribution,  really awesome.

**Pull request merged**
